apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  creationTimestamp: null
  name: postgresql
  namespace: default
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: postgresqls.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: postgresql
        plural: postgresqls
        singular: postgresql
      scope: Namespaced
      versions:
        - name: v1alpha1
          schema:
            openAPIV3Schema:
              properties:
                spec:
                  properties:
                    dbName:
                      default: postgres
                      description: |
                        Database name. A database will be created with this name. The owner of the database will be the teamId.
                      type: string
                    env:
                      default: dev
                      description: |
                        Configures and deploys this PostgreSQL with environment specific configuration. Prod PostgreSQL are configured with backups and more resources.
                      pattern: ^(dev|prod)$
                      type: string
                    namespace:
                      default: default
                      description: |
                        Kubernetes namespace to create the Postgres cluster.
                      type: string
                    teamId:
                      default: acid
                      description: |
                        Team ID. A superuser role will be created with this name.
                      type: string
                  type: object
              type: object
          served: true
          storage: true
  workflows:
    promise:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: promise-configure
            namespace: default
          spec:
            containers:
              - image: ghcr.io/syntasso/promise-postgresql/postgresql-configure-pipeline:v0.1.0
                name: psql-promise-pipeline
    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: instance-configure
            namespace: default
          spec:
            containers:
              - image: ghcr.io/syntasso/promise-postgresql/postgresql-configure-pipeline:v0.1.0
                name: postgresql-configure-pipeline
  destinationSelectors:
    - matchLabels:
        environment: dev
status: {}
