#!/usr/bin/env sh

######
# UNLEASH PROMISE PIPELINE
#####

set -x

name="$(yq eval '.metadata.name' /input/object.yaml)"
namespace="${name}-unleash"
autoscaling="$(yq eval '.spec.autoscaling' /input/object.yaml)"

# Create resource request for a new unleash server
yq eval /resources/unleash-request.yaml > /output/unleash-request.yaml
# setup dbproperties

# Create RR for a new postgres, and set the namespace
# setup namespace, dbname and stuff
yq eval /resources/postgres-request.yaml > /output/postgres-request.yaml
