#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"
set -e

if ! which worker-resource-builder >/dev/null; then
	echo "worker-resource-builder not installed"
	exit 1
fi

if [ ! -d "${PWD}/dependenices" ]; then
  exit 0
fi

promise_contents=$(worker-resource-builder \
 -resources-dir "${pwd}/dependencies" \
      -promise "${pwd}/../promise.yaml")


echo "$promise_contents" > "${PWD}/../promise.yaml"
