#!/usr/bin/env bash

set -eux
pwd="$( cd $(dirname $0)/.. && pwd)"

mkdir -p ${pwd}/configure-pipeline/dependencies

curl -s https://raw.githubusercontent.com/syntasso/promise-postgresql/main/promise.yaml |
    yq '.spec.destinationSelectors[0].matchLabels = {"environment": "dev"}'  > ${pwd}/configure-pipeline/dependencies/postgres-promise.yaml
cp ${pwd}/promises/unleash-server/promise.yaml ${pwd}/configure-pipeline/dependencies/unleash-server-promise.yaml
