#!/usr/bin/env bash

pwd="$( cd $(dirname $0)/.. && pwd)"
set -e

if ! which worker-resource-builder >/dev/null; then
	echo "worker-resource-builder not installed"
	exit 1
fi

if [ ! -d "${pwd}/dependencies" ]; then
  exit 0
fi

promise_contents=$(worker-resource-builder \
  -resources-dir "${pwd}/dependencies" \
	-promise "${pwd}/../promise.yaml")

echo "$promise_contents" > "${pwd}/../promise.yaml"
