#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"

set -e

promise_name="unleash"
pipeline_image="ghcr.io/syntasso/promise-${promise_name}/${promise_name}-configure-pipeline:v0.1.0"

while [ $# -gt 0 ]; do
  case "$1" in
    build)
      docker build \
        --tag "${pipeline_image}" \
        --platform linux/amd64 \
        "${PWD}/configure-pipeline"

      "${PWD}/promises/unleash-server/internal/scripts/pipeline-image" build ;;

    load)
      kind load docker-image "${pipeline_image}" --name platform
      "${PWD}/promises/unleash-server/internal/scripts/pipeline-image" load ;;

    push)
      docker push "${pipeline_image}"
      "${PWD}/promises/unleash-server/internal/scripts/pipeline-image" push ;;

    rmi)
      docker rmi --force "${pipeline_image}"

      "${PWD}/promises/unleash-server/internal/scripts/pipeline-image" rmi ;;

    pull)
      docker pull "${pipeline_image}"
      "${PWD}/promises/unleash-server/internal/scripts/pipeline-image" pull ;;

    *)
      echo "unknown command $1"
      exit 1
      ;;
  esac
  shift
done
