#!/usr/bin/env bash
set -e

test_promise() {
  kubectl wait --for=condition=Established --timeout=60s crd/unleashs.marketplace.kratix.io
  kubectl wait --for=condition=Established --timeout=60s crd/unleashservers.marketplace.kratix.io
  kubectl wait --for=condition=Available --timeout=60s deploy/postgres-operator
}

test_resource_request() {
  kubectl wait --for=condition=Available --timeout=20s deployment/example-unleash -n example-unleash
}

if [ "$1" = "promise" ]; then
  test_promise
else
  test_resource_request
fi
